# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "urllib3"
        versions: [">= 2"] # boto incompatibility
      - dependency-name: "pydantic"
        versions: [">= 2"] # requires migration from v1
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "monthly"
