name: 'Deploy'
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
env:
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_VAR_banana_api_key: "${{ secrets.BANANA_API_KEY }}"
  TF_VAR_banana_model_key: "${{ secrets.BANANA_MODEL_KEY }}"
jobs:
  deploy-app:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        python-version-file: '.tool-versions'
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-versions'
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: terraform init
      run: cd infrastructure && terraform init
    - name: npm install
      run: cd frontend && npm install
    - name: npm run build
      run: cd frontend && npm run build
    - name: terraform apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
